# Generated by Django 5.2 on 2025-04-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_reminder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
